AWSTemplateFormatVersion: '2010-09-09'
Resources:
  # IAM Policy with Dangerous CloudTrail Permissions
  CloudTrailPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: DangerousCloudTrailPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "cloudtrail:StopLogging"
              - "cloudtrail:DeleteTrail"
            Resource: "*"

  # S3 Bucket with Public Access
  PublicS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: public-access-bucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  # EC2 Role with Full S3 Access
  EC2FullS3AccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: FullS3Access
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: "*"

  # IAM Role with Overly Broad EC2 Permissions
  EC2ManagementRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: EC2FullAccess
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - "ec2:RunInstances"
                  - "ec2:TerminateInstances"
                Resource: "*"

  # DynamoDB Table with Public Access
  PublicDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: public-dynamodb-table
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: false
      Tags:
        - Key: PublicAccess
          Value: true
