AWSTemplateFormatVersion: '2010-09-09'
Resources:
  # IAM Policy Resource for Vulnerability Scanning
  VulnerableIAMPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: VulnerablePolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          # Allow critical CloudTrail actions (vulnerability)
          - Effect: Allow
            Action:
              - "cloudtrail:StopLogging"
              - "cloudtrail:DeleteTrail"
            Resource: "*"

          # Allow overly broad S3 permissions
          - Effect: Allow
            Action:
              - "s3:PutObject"
              - "s3:GetObject"
            Resource: "arn:aws:s3:::cloudtrail-logs-bucket/*"

          # Deny sensitive IAM actions (logical error in Deny structure)
          - Effect: Deny
            Action:
              - "iam:CreateRole"
              - "iam:AttachRolePolicy"
            Resource: "*"

          # Allow EC2 instance management with overly broad permissions
          - Effect: Allow
            Action:
              - "ec2:RunInstances"
              - "ec2:TerminateInstances"
            Resource:
              - "arn:aws:ec2:region:account-id:instance/*"
              - "arn:aws:ec2:region:account-id:volume/*"
